### ISSUE TITLE
trying to re-upload a bot gives 500 error

### ISSUE THREAD

**Issue by defunctzombie** [scribd/robot-fruit-hunt#4]
Since there isn't an issue tracker for the website itself, I figured I would post this here.

Trying to upload a bot over an existing one gives a 500 internal server error. Not very nice :(

**Comment by matthiaskramm** [comment]
Hi Roman,

thanks for reporting this! The issue is known, and will be fixed with our deploy at noon.

Happy hacking,

Matthias

-----Original Message-----
From: Roman Shtylman
Sent: Fri, May 25, 2012 at 09:46:41AM -0700
To matthiaskram
Since there isn't an issue tracker for the website itself, I figured I would post this here.

Trying to upload a bot over an existing one gives a 500 internal server error. Not very nice :(

---

Reply to this email directly or view it on GitHub:
https://github.com/scribd/robot-fruit-hunt/issues/4
